name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-xetex

      - name: List files for debugging
        run: find . -type f -name '*.md' -exec echo {} \;

      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdfs
          find . -type f -name '*.md' | while read file; do
            output="pdfs/${file%.md}.pdf"
            mkdir -p "$(dirname "$output")"
            pandoc "$file" -o "$output" --pdf-engine=xelatex
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdfs
          path: pdfs/**/*.pdf
